name: msu
version: 0.2.0.0
synopsis: Monitor Setup Utility
description: Convenient wrapper over xrandr for setting up monitors
homepage: http://github.com/pbrisbin/msu
author: Pat Brisbin <pbrisbin@gmail.com>
maintainer: Pat Brisbin <pbrisbin@gmail.com>
license: MIT

dependencies:
  - base >= 4.8.0 && < 5

extra-doc-files:
  - CHANGELOG.md
  - README.md

ghc-options: -Wall

library:
  source-dirs: src
  dependencies:
   - aeson
   - aeson-casing
   - bytestring
   - parsec
   - process
   - unliftio
   - yaml

executables:
  msu:
    source-dirs: app
    main: Main.hs
    dependencies:
      - directory
      - filepath
      - msu
      - process

tests:
  spec:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - bytestring
      - errors
      - hspec
      - msu
